### ISSUE TITLE
License

### ISSUE THREAD

**Issue by rugk** [PrivateBin/assets#1]
@elrido What do you think which license would be good?
Currently I use CC-BY as embedded in the meta data of the SVGs. What do you think would be a good license for the icon?

**Comment by elrido** [comment]
Thats fine, its a creative work, not code. Will add this to the license file when importing it into main.

**Comment by rugk** [comment]
Yeah, just thought maybe -SA or something similar.
But I also think CC-BY is okay. I'll add the license file.
