### ISSUE TITLE
Minifiy SVGs

### ISSUE THREAD

**Issue by rugk** [PrivateBin/assets#4]
I've added [some minified SVGs](https://github.com/PrivateBin/assets/tree/master/images/minified).

I used http://www.svgminify.com and [SVGO](https://github.com/svg/svgo). However SVGO currently breaks my local image viewer (see https://github.com/svg/svgo/issues/566), but in Firefox it looks good.

So what file might we choose for production?

**Comment by elrido** [comment]
If it works in the browser (looks like they all do), then the smallest one.
