### ISSUE TITLE
Icon looks too orange on Windows

### ISSUE THREAD

**Issue by rugk** [PrivateBin/assets#5]
In Firefox 48.0.1 and Inkscape all icons (even the minified ones, which were not modified) look quite orange now.
Either I don't remember it correctly, but were not they lighter (with more yellow and less orange) before? 

Also the [screenshot here](https://github.com/PrivateBin/assets/issues/3#issuecomment-233544271)  look much lighter...
## PNG

![](https://raw.githubusercontent.com/PrivateBin/assets/535b43a1d34fb57b399e414cf62c6ac8dea700f2/images/preview/icon.png)
# SVG

![svgtooorange](https://cloud.githubusercontent.com/assets/11966684/17830624/249f8ae6-66d1-11e6-9ab4-3d19c34333c8.PNG)
![tooorangeicon](https://cloud.githubusercontent.com/assets/11966684/17830625/24a42948-66d1-11e6-823d-ae8cf474eff4.PNG)

[Live version here](https://github.com/PrivateBin/assets/blob/a5c85b24ad71ebca8dff58923e2b4fef59fb7a64/images/svgs/icon.svg)

**Comment by rugk** [comment]
So it looks as if https://github.com/PrivateBin/assets/commit/6e04defdb826e67905b05e6fc0e3c755386945dc?short_path=2ddab41#diff-2ddab4109dfc0a5215c8fe357d68fc47 would have introduced this, however at that time it did not look like this.

**Comment by rugk** [comment]
What's worse is that it seems to look okay on Chromium (Windows x64). The following image is  a screenshot of https://github.com/PrivateBin/assets/commit/6e04defdb826e67905b05e6fc0e3c755386945dc?short_path=2ddab41#diff-2ddab4109dfc0a5215c8fe357d68fc47:
![chromiumsvg](https://cloud.githubusercontent.com/assets/11966684/17830644/a10f5958-66d1-11e6-8b44-c2e746b47f30.PNG)

Again note that the icon was too orange on
- Firefox 48.0.1 on Windows 7 x64
- and Inkscape 0.91 on Windows 7 x64

Here is how it looks in Inkscape:
![inkscapetooorange](https://cloud.githubusercontent.com/assets/11966684/17830656/f87b168c-66d1-11e6-8e36-dbde74af196d.PNG)

**Comment by rugk** [comment]
It also looks like this in the Readme:
![readmetooorange](https://cloud.githubusercontent.com/assets/11966684/17830681/05321e42-66d3-11e6-9807-6c61283ae90e.PNG)

**Comment by rugk** [comment]
It looks correct in Firefox 48.0.1 on Linux.

Also in Inkscape (v0.48) it looks slightly better on Linux:
![linuxinkscape](https://cloud.githubusercontent.com/assets/11966684/17830990/d6de175c-66dd-11e6-962e-1c2e5d637033.png)

**Comment by rugk** [comment]
However as you can see from the last screenshot also Inkscape on Linux does it wrong...

**Comment by rugk** [comment]
It could be the radius attribute, which is causing issues. I am tinkling around a bit in the branch [`gradientsfix`](https://github.com/PrivateBin/assets/tree/gradientsfix).

Here is how it looks in Inkscape on Linux with (left) and without (right) the radius attribute:
![radiusvalue](https://cloud.githubusercontent.com/assets/11966684/17831833/61b2fd14-66f4-11e6-80bb-aa487dde6890.png)

BTW: Sorry that this image is so blue.

**Comment by rugk** [comment]
However the new version looks not so nice anymore in browsers/OSes where the previous version has been rendered correctly:
![difference](https://cloud.githubusercontent.com/assets/11966684/17831856/1f08266e-66f5-11e6-87d3-445143395f8c.png)

**Comment by rugk** [comment]
Okay, I have a assumption what is the issue: One implementation measures everything from the outside one from the inside.
So with https://github.com/PrivateBin/assets/commit/72facc2f18d38491627efc8a9218d167f963ddb4 I now fixed everything on Windows. (tested with Firefox, Inkscape & IE)
Let's see how this looks on Linux.

**Comment by rugk** [comment]
Okay, so on Linux Inkscape it looks - surprisingly - okay.
On Firefox Linux it looks broken as [I already mentioned here](https://github.com/PrivateBin/assets/issues/5#issuecomment-241203868), however _as I use some quite outdated libs here_ I rather think this is an issue in the Linux implementation and I think the Windows rendering is correct.

If anyone has more information (such as what version is rendered correctly) I would happily appreciate any comments.

For now I consider this issue fixed.

**Comment by elrido** [comment]
Personally I like it better in orange.

**Comment by rugk** [comment]
Well... I already fixed them and they are still mainly orange. Just the yellow light in the middle is bigger.
Just have a look at the current master and if you think it does not look nice, just do a PR or so... :smiley:
